#!/usr/bin/env node
/**
 * Build script for the NNF icon library.
 *
 * Reads the source SVGs in `icons/` (the single source of truth) and emits,
 * into `dist/`, every consumable form of the library:
 *
 *   - sprite.svg            an SVG sprite of <symbol> elements
 *   - icons.json            metadata + raw markup for every icon
 *   - data.mjs / .cjs / .d.ts   framework-agnostic data API
 *   - react.mjs / .cjs / .d.ts  one React component per icon
 *   - index.mjs / .cjs / .d.ts  package entrypoint (re-exports data API)
 *
 * It deliberately has zero runtime/build dependencies so it runs anywhere
 * Node does, with no install step.
 */
import { readdirSync, readFileSync, writeFileSync, mkdirSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const iconsDir = join(root, 'icons');
const distDir = join(root, 'dist');

// Presentation attributes shared by every icon's wrapper element.
const ATTRS = {
  viewBox: '0 0 24 24',
  fill: 'none',
  stroke: 'currentColor',
  'stroke-width': '2',
  'stroke-linecap': 'round',
  'stroke-linejoin': 'round',
};

const toPascal = (name) =>
  name.replace(/(^|-)([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const toCamelAttr = (name) =>
  name.replace(/-([a-z])/g, (_, c) => c.toUpperCase());

/** Pull the inner markup out of an `<svg>...</svg>` source file. */
function innerBody(svg) {
  const m = svg.match(/<svg[^>]*>([\s\S]*?)<\/svg>/i);
  return (m ? m[1] : '').replace(/\s+/g, ' ').replace(/>\s+</g, '><').trim();
}

/** Parse the leaf elements of a body into `{ tag, attrs }` records. */
function parseElements(body) {
  const els = [];
  const re = /<([a-zA-Z]+)((?:\s+[\w:-]+="[^"]*")*)\s*\/?>/g;
  let m;
  while ((m = re.exec(body))) {
    const tag = m[1];
    const attrs = {};
    const ar = /([\w:-]+)="([^"]*)"/g;
    let a;
    while ((a = ar.exec(m[2]))) attrs[a[1]] = a[2];
    els.push({ tag, attrs });
  }
  return els;
}

// ---------------------------------------------------------------------------
// Load sources
// ---------------------------------------------------------------------------
const files = readdirSync(iconsDir).filter((f) => f.endsWith('.svg')).sort();
if (files.length === 0) {
  console.error('No SVG sources found in icons/. Nothing to build.');
  process.exit(1);
}

const icons = files.map((file) => {
  const name = file.replace(/\.svg$/, '');
  const raw = readFileSync(join(iconsDir, file), 'utf8');
  const body = innerBody(raw);
  const attrStr = Object.entries(ATTRS).map(([k, v]) => `${k}="${v}"`).join(' ');
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" ${attrStr}>${body}</svg>`;
  return {
    name,
    component: toPascal(name),
    viewBox: ATTRS.viewBox,
    body,
    svg,
    elements: parseElements(body),
  };
});

rmSync(distDir, { recursive: true, force: true });
mkdirSync(distDir, { recursive: true });

const banner = '/* AUTO-GENERATED by scripts/build.mjs. Do not edit by hand. */\n';

// ---------------------------------------------------------------------------
// sprite.svg
// ---------------------------------------------------------------------------
const symbolAttrs = Object.entries(ATTRS).map(([k, v]) => `${k}="${v}"`).join(' ');
const sprite =
  `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n` +
  icons
    .map((i) => `  <symbol id="nnf-${i.name}" ${symbolAttrs}>${i.body}</symbol>`)
    .join('\n') +
  `\n</svg>\n`;
writeFileSync(join(distDir, 'sprite.svg'), sprite);

// ---------------------------------------------------------------------------
// icons.json
// ---------------------------------------------------------------------------
const meta = icons.map(({ name, component, viewBox, body, svg }) => ({
  name,
  component,
  viewBox,
  body,
  svg,
}));
writeFileSync(join(distDir, 'icons.json'), JSON.stringify(meta, null, 2) + '\n');

// ---------------------------------------------------------------------------
// data.mjs / data.cjs / data.d.ts  (framework-agnostic)
// ---------------------------------------------------------------------------
const dataObject =
  '{\n' +
  icons
    .map(
      (i) =>
        `  ${JSON.stringify(i.name)}: { name: ${JSON.stringify(i.name)}, ` +
        `viewBox: ${JSON.stringify(i.viewBox)}, ` +
        `body: ${JSON.stringify(i.body)}, ` +
        `svg: ${JSON.stringify(i.svg)} }`
    )
    .join(',\n') +
  '\n}';

writeFileSync(
  join(distDir, 'data.mjs'),
  banner +
    `export const icons = ${dataObject};\n` +
    `export const iconNames = Object.keys(icons);\n` +
    `export function getIcon(name) { return icons[name]; }\n`
);
writeFileSync(
  join(distDir, 'data.cjs'),
  banner +
    `const icons = ${dataObject};\n` +
    `const iconNames = Object.keys(icons);\n` +
    `function getIcon(name) { return icons[name]; }\n` +
    `module.exports = { icons, iconNames, getIcon };\n`
);
writeFileSync(
  join(distDir, 'data.d.ts'),
  banner +
    `export interface IconData {\n` +
    `  name: string;\n  viewBox: string;\n  body: string;\n  svg: string;\n}\n` +
    `export type IconName =\n` +
    icons.map((i) => `  | ${JSON.stringify(i.name)}`).join('\n') +
    `;\n` +
    `export declare const icons: Record<IconName, IconData>;\n` +
    `export declare const iconNames: IconName[];\n` +
    `export declare function getIcon(name: IconName): IconData | undefined;\n`
);

// ---------------------------------------------------------------------------
// react.mjs / react.cjs / react.d.ts
// ---------------------------------------------------------------------------
function elementsToCreateCalls(els, fn) {
  return els
    .map((el, idx) => {
      const props = { key: idx };
      for (const [k, v] of Object.entries(el.attrs)) props[toCamelAttr(k)] = v;
      return `${fn}(${JSON.stringify(el.tag)}, ${JSON.stringify(props)})`;
    })
    .join(', ');
}

const reactDefaults = JSON.stringify({
  xmlns: 'http://www.w3.org/2000/svg',
  viewBox: ATTRS.viewBox,
  fill: ATTRS.fill,
  stroke: ATTRS.stroke,
  strokeWidth: ATTRS['stroke-width'],
  strokeLinecap: ATTRS['stroke-linecap'],
  strokeLinejoin: ATTRS['stroke-linejoin'],
});

function reactModule({ esm }) {
  const imp = esm
    ? `import { createElement as h, forwardRef } from 'react';\n`
    : `const { createElement: h, forwardRef } = require('react');\n`;
  const exp = (name, expr) =>
    esm ? `export const ${name} = ${expr};\n` : `const ${name} = ${expr};\n`;

  let out = banner + imp;
  out += `const DEFAULTS = ${reactDefaults};\n`;
  out +=
    `function make(displayName, children) {\n` +
    `  const Icon = forwardRef(function (props, ref) {\n` +
    `    const { size = 24, title, ...rest } = props || {};\n` +
    `    return h('svg', {\n` +
    `      ...DEFAULTS, width: size, height: size, ref,\n` +
    `      'aria-hidden': title ? undefined : true,\n` +
    `      role: title ? 'img' : undefined, ...rest,\n` +
    `    }, title ? h('title', { key: 'title' }, title) : null, ...children);\n` +
    `  });\n` +
    `  Icon.displayName = displayName;\n` +
    `  return Icon;\n` +
    `}\n`;

  for (const i of icons) {
    out += exp(
      i.component,
      `make(${JSON.stringify(i.component)}, [${elementsToCreateCalls(i.elements, 'h')}])`
    );
  }
  if (!esm) {
    out += `module.exports = { ${icons.map((i) => i.component).join(', ')} };\n`;
  }
  return out;
}

writeFileSync(join(distDir, 'react.mjs'), reactModule({ esm: true }));
writeFileSync(join(distDir, 'react.cjs'), reactModule({ esm: false }));
writeFileSync(
  join(distDir, 'react.d.ts'),
  banner +
    `import * as React from 'react';\n` +
    `export interface IconProps extends React.SVGProps<SVGSVGElement> {\n` +
    `  /** Width and height in pixels. Defaults to 24. */\n  size?: number | string;\n` +
    `  /** Accessible label. When set the icon is exposed as role="img". */\n  title?: string;\n}\n` +
    `export type IconComponent = React.ForwardRefExoticComponent<\n` +
    `  IconProps & React.RefAttributes<SVGSVGElement>\n>;\n` +
    icons.map((i) => `export declare const ${i.component}: IconComponent;`).join('\n') +
    '\n'
);

// ---------------------------------------------------------------------------
// index.* (package entrypoint -> data API)
// ---------------------------------------------------------------------------
writeFileSync(join(distDir, 'index.mjs'), banner + `export * from './data.mjs';\n`);
writeFileSync(
  join(distDir, 'index.cjs'),
  banner + `module.exports = require('./data.cjs');\n`
);
writeFileSync(join(distDir, 'index.d.ts'), banner + `export * from './data';\n`);

console.log(
  `Built ${icons.length} icons -> dist/ (sprite.svg, icons.json, data.*, react.*, index.*)`
);
